#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses"
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#pragma GCC diagnostic ignored "-Wsign-compare"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#pragma GCC diagnostic ignored "-Wunused-parameter"
extern "C"
{
#include "f2c.h"

static integer c__2 = 2;
static integer c__1 = 1;
static integer c__0 = 0;
static integer c_n1 = -1;
static doublecomplex c_b1 = {1.,0.};
static doublecomplex c_b2 = {0.,0.};
static doublecomplex c_b5 = {1.,0.};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wwrite-strings"
#include "c/lapack/zggev.c"
#include "c/lapack/xerbla.c"
#include "c/lapack/dlamch.c"
#include "c/lapack/dlabad.c"
#include "c/lapack/zlange.c"
#include "c/lapack/zlascl.c"
#include "c/lapack/zggbal.c"
#include "c/lapack/zgeqrf.c"
#include "c/lapack/zunmqr.c"
#include "c/lapack/zlaset.c"
#include "c/lapack/zlacpy.c"
#include "c/lapack/zungqr.c"
#include "c/lapack/zgghrd.c"
#include "c/lapack/zhgeqz.c"
#include "c/lapack/ztgevc.c"
#include "c/lapack/zggbak.c"
#include "c/lapack/tstiee.c"
#include "c/lapack/zlassq.c"
#include "c/lapack/disnan.c"
#include "c/lapack/zgeqr2.c"
#include "c/lapack/zlarft.c"
#include "c/lapack/zlarfb.c"
#include "c/lapack/zunm2r.c"
#include "c/lapack/zung2r.c"
#include "c/lapack/zlartg.c"
#include "c/lapack/zrot.c"
#include "c/lapack/zlanhs.c"
#include "c/lapack/zladiv.c"
#include "c/lapack/zlarfp.c"
#include "c/lapack/zlarf.c"
#include "c/lapack/zlacgv.c"
#include "c/lapack/ilazlr.c"
#include "c/lapack/ilazlc.c"
#include "c/lapack/dlapy2.c"
#include "c/lapack/dladiv.c"
#include "c/lapack/dznrm2.c"
#include "c/lapack/dlapy3.c"
#include "c/lapack/lsame.c"
#include "c/lapack/dlaisnan.c"

#include "c/blas/zgerc.c"
#include "c/blas/ztrmv.c"
#include "c/blas/zgemv.c"
#include "c/blas/ztrmm.c"
#include "c/blas/zgemm.c"
#include "c/blas/dcabs1.c"
#include "c/blas/zswap.c"
#include "c/blas/ddot.c"
#include "c/blas/dscal.c"
#include "c/blas/daxpy.c"
#include "c/blas/izamax.c"
#include "c/blas/zscal.c"
#include "c/blas/zdscal.c"
#include "c/blas/zcopy.c"
#pragma GCC diagnostic pop

#include "c/f2c/d_imag.c"
#include "c/f2c/s_copy.c"
#include "c/f2c/s_cmp.c"
#include "c/f2c/pow_di.c"
#include "c/f2c/wsfe.c"
#include "c/f2c/fmt.c"
#include "c/f2c/sfe.c"
#include "c/f2c/z_abs.c"
#include "c/f2c/d_lg10.c"
#include "c/f2c/d_sign.c"
#include "c/f2c/wsle.c"
#include "c/f2c/wrtfmt.c"
#include "c/f2c/rdfmt.c"
#undef L
#include "c/f2c/s_cat.c"
#include "c/f2c/d_cnjg.c"
#include "c/f2c/z_div.c"
#include "c/f2c/pow_zi.c"
#include "c/f2c/z_sqrt.c"
#include "c/f2c/dolio.c"
#include "c/f2c/err.c"
#include "c/f2c/endfile.c"
#include "c/f2c/open.c"
#include "c/f2c/sig_die.c"
#include "c/f2c/cabs.c"
#include "c/f2c/lread.c"
#include "c/f2c/lwrite.c"
#include "c/f2c/fmtlib.c"
#include "c/f2c/wref.c"
#include "c/f2c/f77_aloc.c"
#include "c/f2c/util.c"
#include "c/f2c/close.c"
#include "c/f2c/rsfe.c"
#include "c/f2c/exit_.c"
}
#pragma GCC diagnostic pop
