extern "C"
{
static integer c__2 = 2;
static integer c__1 = 1;
static integer c__0 = 0;
static integer c_n1 = -1;
static doublecomplex c_b1 = {1.,0.};
static doublecomplex c_b2 = {0.,0.};
static doublecomplex c_b5 = {1.,0.};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wwrite-strings"
#include "c/zggev.c"
//#include "c/ilaenv.c"
#include "c/xerbla.c"
#include "c/dlamch.c"
#include "c/dlabad.c"
#include "c/zlange.c"
#include "c/zlascl.c"
#include "c/zggbal.c"
#include "c/zgeqrf.c"
#include "c/zunmqr.c"
#include "c/zlaset.c"
#include "c/zlacpy.c"
#include "c/zungqr.c"
#include "c/zgghrd.c"
#include "c/zhgeqz.c"
#include "c/ztgevc.c"
#include "c/zggbak.c"
#include "c/tstiee.c"
#include "c/zlassq.c"
#include "c/disnan.c"
#include "c/zgeqr2.c"
#include "c/zlarft.c"
#include "c/zlarfb.c"
#include "c/zunm2r.c"
#include "c/zung2r.c"
#include "c/zlartg.c"
#include "c/zrot.c"
#include "c/zlanhs.c"
#include "c/zladiv.c"
#include "c/zgemv.c"
#include "c/zlarfp.c"
#include "c/zlarf.c"
#include "c/zlacgv.c"
#include "c/ztrmv.c"
#include "c/ilazlr.c"
#include "c/ilazlc.c"
#include "c/ztrmm.c"
#include "c/zgemm.c"
#include "c/dlapy2.c"
#include "c/dladiv.c"
#include "c/dznrm2.c"
#include "c/dlapy3.c"
#include "c/zgerc.c"
#include "c/dcabs1.c"
#pragma GCC diagnostic pop

#include "c/lsame.c"
#include "c/d_imag.c"
#include "c/s_copy.c"
#include "c/s_cmp.c"
#include "c/pow_di.c"
#include "c/wsfe.c"
#include "c/fmt.c"
#include "c/sfe.c"
#include "c/z_abs.c"
#include "c/d_lg10.c"
#include "c/zswap.c"
#include "c/ddot.c"
#include "c/dscal.c"
#include "c/daxpy.c"
#include "c/izamax.c"
#include "c/d_sign.c"
#include "c/zdscal.c"
#include "c/wsle.c"
#include "c/wrtfmt.c"
#include "c/rdfmt.c"
#undef L
#include "c/s_cat.c"
#include "c/d_cnjg.c"
#include "c/zscal.c"
#include "c/z_div.c"
#include "c/pow_zi.c"
#include "c/z_sqrt.c"
#include "c/dolio.c"
#include "c/dlaisnan.c"
#include "c/zcopy.c"
#include "c/err.c"
#include "c/endfile.c"
#include "c/open.c"
//#include "c/main.c"
#include "c/sig_die.c"
#include "c/cabs.c"
#include "c/lread.c"
#include "c/lwrite.c"
#include "c/fmtlib.c"
#include "c/wref.c"
#include "c/f77_aloc.c"
#include "c/util.c"
#include "c/close.c"
#include "c/rsfe.c"
#include "c/exit_.c"
}
